import type { ItemDef } from "../types";

export const ITEMS: ItemDef[] = [
  {
    id: "c_rations_bulk",
    name: "Bulk rations crate",
    kind: "common",
    description: "+18 rations",
    price: 140,
    grants: { rations: 18 },
  },
  {
    id: "c_water_drums",
    name: "Water drums",
    kind: "common",
    description: "+16 water",
    price: 120,
    grants: { water: 16 },
  },
  {
    id: "c_medkit",
    name: "Field medkit",
    kind: "common",
    description: "+5 meds",
    price: 200,
    grants: { meds: 5 },
  },
  {
    id: "c_parts",
    name: "Machine parts bundle",
    kind: "common",
    description: "+8 parts",
    price: 160,
    grants: { parts: 8 },
  },
  {
    id: "c_fuel_jerry",
    name: "Jerrycans (ethanol mix)",
    kind: "common",
    description: "+10 fuel",
    price: 150,
    grants: { fuel: 10 },
  },
  {
    id: "u_geiger",
    name: "Salvaged Geiger counter",
    kind: "unique",
    description: "Rad checks get +4 effective bonus.",
    price: 320,
    tags: ["geiger"],
  },
  {
    id: "u_maps",
    name: "Pre-war highway folios",
    kind: "unique",
    description: "Travel legs cost slightly less fuel.",
    price: 260,
    tags: ["maps"],
  },
  {
    id: "u_rebreather",
    name: "Cracked rebreather",
    kind: "unique",
    description: "Black-rain events safer; once per run auto-soak 25 rads.",
    price: 410,
    tags: ["rebreather"],
  },
  {
    id: "u_lucky_coin",
    name: "Charred lucky coin",
    kind: "unique",
    description: "Reroll one failed trait check per run (consumed in-engine via flag).",
    price: 180,
    tags: ["luckyCoin"],
  },
  {
    id: "u_forge_kit",
    name: "Forgery stylus + laminate",
    kind: "unique",
    description: "Embark paper checks: -2 effective DC once.",
    price: 350,
    tags: ["forgeKit"],
  },
  {
    id: "u_saint_patch",
    name: "Saint-of-Wires patch",
    kind: "unique",
    description: "Mechanic checks +3 if morale > 40.",
    price: 220,
    tags: ["saintPatch"],
  },
  {
    id: "u_rad_blanket",
    name: "Lead-thread blanket",
    kind: "unique",
    description: "-15% rad gain from travel ticks.",
    price: 290,
    tags: ["radBlanket"],
  },
  {
    id: "u_signal_flare",
    name: "Aerospace signal flare",
    kind: "unique",
    description: "Unlocks special rescue branch in approach biome.",
    price: 240,
    tags: ["signalFlare"],
  },
  {
    id: "u_dog_tags",
    name: "Dog tags (not yours)",
    kind: "unique",
    description: "Negotiator checks +2; riskier if flagged.",
    price: 90,
    tags: ["dogTags"],
  },
];

export function getItem(id: string): ItemDef | undefined {
  return ITEMS.find((i) => i.id === id);
}
