import type { ItemDef } from "../types";

export const ITEMS: ItemDef[] = [
  // ── Common (buy multiples; grants starting resources) ────────────────────
  {
    id: "c_rations_bulk",
    name: "Bulk rations crate",
    kind: "common",
    description: "+42 rations",
    price: 140,
    grants: { rations: 42 },
  },
  {
    id: "c_medkit",
    name: "Field medkit",
    kind: "common",
    description: "+5 meds",
    price: 200,
    grants: { meds: 5 },
  },
  {
    id: "c_parts",
    name: "Machine parts bundle",
    kind: "common",
    description: "+8 parts",
    price: 160,
    grants: { parts: 8 },
  },
  {
    id: "c_fuel_jerry",
    name: "Jerrycans (ethanol mix)",
    kind: "common",
    description: "+28 fuel",
    price: 150,
    grants: { fuel: 28 },
  },

  // ── Unique (max 1; passive convoy-wide rules-changers) ────────────────────
  {
    id: "u_geiger",
    name: "Salvaged Geiger counter",
    kind: "unique",
    description: "Warns of hot zones. Reduces daily rad gain by ~15%.",
    price: 320,
    tags: ["geiger"],
  },
  {
    id: "u_maps",
    name: "Pre-war highway folios",
    kind: "unique",
    description: "Travel legs cost 15% less fuel.",
    price: 260,
    tags: ["maps"],
  },
  {
    id: "u_rebreather",
    name: "Cracked rebreather",
    kind: "unique",
    description: "Absorbs one bad rad surge per run. Helps in toxic zones.",
    price: 410,
    tags: ["rebreather"],
  },
  {
    id: "u_lucky_coin",
    name: "Charred lucky coin",
    kind: "unique",
    description: "After a failed event roll, redraw once at the same odds (once per run).",
    price: 180,
    tags: ["luckyCoin"],
  },
  {
    id: "u_forge_kit",
    name: "Forgery stylus + laminate",
    kind: "unique",
    description: "+10% to event choices requiring paperwork or authority.",
    price: 350,
    tags: ["forgeKit"],
  },
  {
    id: "u_rad_blanket",
    name: "Lead-thread blanket",
    kind: "unique",
    description: "Reduces rad accumulation from harsh travel days.",
    price: 290,
    tags: ["radBlanket"],
  },
  {
    id: "u_signal_flare",
    name: "Aerospace signal flare",
    kind: "unique",
    description: "Unlocks a rescue choice in the port sprawl approach.",
    price: 240,
    tags: ["signalFlare"],
  },
  {
    id: "u_antibiotics",
    name: "Pre-war antibiotic course",
    kind: "unique",
    description: "Auto-cures one sickness when a party member falls ill (then spent).",
    price: 310,
    tags: ["antibiotics"],
  },

  // ── Personal (assign to one party member; gives them individual bonuses) ──
  // These are stat-based and do not require any traits.
  {
    id: "pi_armour_vest",
    name: "Scavenged armour vest",
    kind: "personal",
    description: "+20 max HP and 15% less likely to get injured on the road.",
    price: 340,
    memberEffect: { maxHealthBonus: 20, injuryResistance: 15 },
  },
  {
    id: "pi_stim_injector",
    name: "Combat stim injector",
    kind: "personal",
    description: "+15 max HP and heals 5 extra HP each time the party rests.",
    price: 220,
    memberEffect: { maxHealthBonus: 15, dailyHealBonus: 5 },
  },
  {
    id: "pi_hunting_kit",
    name: "Hunter's kit",
    kind: "personal",
    description: "+25% to Search for Food. Good at finding what's edible out there.",
    price: 195,
    memberEffect: { scavengeBonus: 25 },
  },
  {
    id: "pi_ration_belt",
    name: "Compressed ration belt",
    kind: "personal",
    description: "This person eats one fewer ration per day. Trained to manage on less.",
    price: 175,
    memberEffect: { rationReduction: 1 },
  },
  {
    id: "pi_iron_boots",
    name: "Reinforced iron boots",
    kind: "personal",
    description: "+3 km per travel day. Built for the long haul.",
    price: 210,
    memberEffect: { travelKmBonus: 3 },
  },
  {
    id: "pi_medic_bag",
    name: "Field medic's bag",
    kind: "personal",
    description: "Heals 10 extra HP on rest days. Also adds 3 days to sickness timers.",
    price: 240,
    memberEffect: { dailyHealBonus: 10, sicknessResistDays: 3 },
  },
  {
    id: "pi_trade_papers",
    name: "Faction trade papers",
    kind: "personal",
    description: "+25% on Attempt to Trade. Old credentials open doors.",
    price: 185,
    memberEffect: { tradeBonus: 25 },
  },
  {
    id: "pi_comfort_kit",
    name: "Personal comfort kit",
    kind: "personal",
    description: "+15 starting morale. Small familiar things keep spirits up.",
    price: 120,
    memberEffect: { moraleBonus: 15 },
  },
  {
    id: "pi_lucky_charm",
    name: "Wire-wrapped lucky charm",
    kind: "personal",
    description: "+10% Search for Food and +10% Trade. Generally lucky.",
    price: 130,
    memberEffect: { scavengeBonus: 10, tradeBonus: 10 },
  },
  {
    id: "pi_hazmat_liner",
    name: "Hazmat underlayer",
    kind: "personal",
    description: "Sickness lasts 5 fewer days before turning fatal for this person.",
    price: 200,
    memberEffect: { sicknessResistDays: 5 },
  },
];

export function getItem(id: string): ItemDef | undefined {
  return ITEMS.find((i) => i.id === id);
}
