import type { ItemDef } from "../types";

export const ITEMS: ItemDef[] = [
  // ── Common (buy multiples; grants starting resources) ────────────────────
  {
    id: "c_rations_bulk",
    name: "Bulk rations crate",
    kind: "common",
    description: "+18 rations",
    price: 140,
    grants: { rations: 18 },
  },
  {
    id: "c_water_drums",
    name: "Water drums",
    kind: "common",
    description: "+16 water",
    price: 120,
    grants: { water: 16 },
  },
  {
    id: "c_medkit",
    name: "Field medkit",
    kind: "common",
    description: "+5 meds",
    price: 200,
    grants: { meds: 5 },
  },
  {
    id: "c_parts",
    name: "Machine parts bundle",
    kind: "common",
    description: "+8 parts",
    price: 160,
    grants: { parts: 8 },
  },
  {
    id: "c_fuel_jerry",
    name: "Jerrycans (ethanol mix)",
    kind: "common",
    description: "+10 fuel",
    price: 150,
    grants: { fuel: 10 },
  },

  // ── Unique (max 1; passive rules-changers for the whole party) ────────────
  {
    id: "u_geiger",
    name: "Salvaged Geiger counter",
    kind: "unique",
    description: "Rad checks get +8% bonus. Also helps when rads > 45.",
    price: 320,
    tags: ["geiger"],
  },
  {
    id: "u_maps",
    name: "Pre-war highway folios",
    kind: "unique",
    description: "Travel legs cost 15% less fuel.",
    price: 260,
    tags: ["maps"],
  },
  {
    id: "u_rebreather",
    name: "Cracked rebreather",
    kind: "unique",
    description: "Black-rain events safer; once per run absorbs a rad surge.",
    price: 410,
    tags: ["rebreather"],
  },
  {
    id: "u_lucky_coin",
    name: "Charred lucky coin",
    kind: "unique",
    description: "After a failed check, redraw once from the same odds (once per run).",
    price: 180,
    tags: ["luckyCoin"],
  },
  {
    id: "u_forge_kit",
    name: "Forgery stylus + laminate",
    kind: "unique",
    description: "Negotiator checks get +6% once (embark and approach).",
    price: 350,
    tags: ["forgeKit"],
  },
  {
    id: "u_saint_patch",
    name: "Saint-of-Wires patch",
    kind: "unique",
    description: "Mechanic checks +8% when any party member has morale > 40.",
    price: 220,
    tags: ["saintPatch"],
  },
  {
    id: "u_rad_blanket",
    name: "Lead-thread blanket",
    kind: "unique",
    description: "Reduces rad gain from travel by ~15%.",
    price: 290,
    tags: ["radBlanket"],
  },
  {
    id: "u_signal_flare",
    name: "Aerospace signal flare",
    kind: "unique",
    description: "Unlocks a rescue choice in the port sprawl approach.",
    price: 240,
    tags: ["signalFlare"],
  },
  {
    id: "u_dog_tags",
    name: "Dog tags (not yours)",
    kind: "unique",
    description: "Negotiator checks +6%. Unknown previous owner.",
    price: 90,
    tags: ["dogTags"],
  },
  {
    id: "u_antibiotics",
    name: "Pre-war antibiotic course",
    kind: "unique",
    description: "Cures one sickness automatically when someone falls ill (then spent).",
    price: 310,
    tags: ["antibiotics"],
  },

  // ── Personal (assign to one party member; gives them individual bonuses) ─
  {
    id: "pi_stim_injector",
    name: "Combat stim injector",
    kind: "personal",
    description: "+15 max HP. Assigned member is hardier.",
    price: 200,
    memberEffect: { maxHealthBonus: 15 },
  },
  {
    id: "pi_hazmat_liner",
    name: "Hazmat underlayer",
    kind: "personal",
    description: "Sickness adds +5 extra days before it turns fatal for this member.",
    price: 230,
    memberEffect: { sicknessResistDays: 5 },
  },
  {
    id: "pi_field_manual",
    name: "Crinkled field manual",
    kind: "personal",
    description: "+8% to all skill checks when this member is the specialist.",
    price: 180,
    memberEffect: { checkBonus: 8 },
  },
  {
    id: "pi_comfort_kit",
    name: "Personal comfort kit",
    kind: "personal",
    description: "+10 starting morale for this member.",
    price: 120,
    memberEffect: { moraleBonus: 10 },
  },
  {
    id: "pi_armour_vest",
    name: "Scavenged armour vest",
    kind: "personal",
    description: "+20 max HP. Heavy but worth it on the front line.",
    price: 340,
    memberEffect: { maxHealthBonus: 20 },
  },
  {
    id: "pi_field_knife",
    name: "Notched field knife",
    kind: "personal",
    description: "+10 max HP and +5% on checks for this member.",
    price: 140,
    memberEffect: { maxHealthBonus: 10, checkBonus: 5 },
  },
  {
    id: "pi_lucky_charm",
    name: "Wire-wrapped charm",
    kind: "personal",
    description: "+6% checks and +8 morale for this member.",
    price: 120,
    memberEffect: { checkBonus: 6, moraleBonus: 8 },
  },
  {
    id: "pi_goggles",
    name: "Welder's goggles",
    kind: "personal",
    description: "+10% when this member leads navigator or engineer checks.",
    price: 145,
    memberEffect: { checkBonus: 10 },
  },
  {
    id: "pi_tool_belt",
    name: "Salvaged tool belt",
    kind: "personal",
    description: "+12% when this member leads mechanic checks.",
    price: 170,
    memberEffect: { checkBonus: 12 },
  },
  {
    id: "pi_rad_patches",
    name: "Rad-absorb patches",
    kind: "personal",
    description: "+4 sickness resist days and +6 max HP.",
    price: 185,
    memberEffect: { sicknessResistDays: 4, maxHealthBonus: 6 },
  },
  {
    id: "pi_scavengers_pack",
    name: "Scavenger's haul pack",
    kind: "personal",
    description: "+10% scavenger checks and +6 morale.",
    price: 165,
    memberEffect: { checkBonus: 10, moraleBonus: 6 },
  },
  {
    id: "pi_pharmacist_satchel",
    name: "Pharmacist's satchel",
    kind: "personal",
    description: "+12% medic checks and +5 sickness resist days.",
    price: 190,
    memberEffect: { checkBonus: 12, sicknessResistDays: 5 },
  },
  {
    id: "pi_negotiator_pin",
    name: "Faction liaison pin",
    kind: "personal",
    description: "+10% negotiator checks for this member.",
    price: 130,
    memberEffect: { checkBonus: 10 },
  },
  {
    id: "pi_dog_tags_charm",
    name: "Stranger's dog tags",
    kind: "personal",
    description: "+8 morale. Someone else's name is etched inside.",
    price: 90,
    memberEffect: { moraleBonus: 8, checkBonus: 4 },
  },
];

export function getItem(id: string): ItemDef | undefined {
  return ITEMS.find((i) => i.id === id);
}
